"""
fishstick NLP Extensions Module

Advanced NLP tools including:
- Tokenizers: BPE, WordPiece, SentencePiece
- Position Encoding: RoPE, ALiBi, Relative Position
- Efficiency: Gradient Checkpointing, Sparse Attention, Flash Attention
- Augmentation: Back Translation, Synonym Replacement, Random Edits, Contextual
- Similarity: Cosine, Levenshtein, BLEU, ROUGE, BERTScore
"""

from fishstick.nlp_extensions.tokenizers import (
    BPETokenizer,
    AdaptiveBPETokenizer,
    ByteLevelBPETokenizer,
    WordPieceTokenizer,
    FastWordPieceTokenizer,
    BertWordPieceTokenizer,
    SentencePieceTokenizer,
    UnigramSentencePiece,
    BPESentencePiece,
)

from fishstick.nlp_extensions.position_encoding import (
    RotaryPositionalEmbedding,
    RotaryEmbedding,
    LinearRoPE,
    YaRNScalingRotaryEmbedding,
    apply_rotary_pos_emb,
    MultiHeadRotaryAttention,
    ALiBiAttention,
    ALiBiPositionalEmbedding,
    ALiBiMultiHeadAttention,
    AliBiFlashAttention,
    build_alibi_bias,
    RelativePositionBias,
    SinusoidalRelativePositionBias,
    RelativePositionMultiHeadAttention,
    T5RelativePositionBias,
    ShawRelativePosition,
    RelativePositionKeyValue,
    relative_position_bucket,
)

from fishstick.nlp_extensions.efficiency import (
    GradientCheckpointing,
    CheckpointWrapper,
    ModularGradientCheckpointing,
    checkpoint_wrapper,
    create_gradient_checkpointing_function,
    MixedPrecisionCheckpointing,
    SelectiveCheckpointing,
    RecomputationScheduler,
    SparseAttention,
    SlidingWindowAttention,
    BlockSparseAttention,
    DilatedAttention,
    GlobalLocalAttention,
    RandomAttention,
    SparseMultiHeadAttention,
    BigBirdAttention,
    FlashAttention,
    FlashAttentionV2,
    MemoryEfficientAttention,
    FlashMultiHeadAttention,
    FlashAttentionWithPdrop,
    is_flash_attn_available,
    create_flash_attention,
)

from fishstick.nlp_extensions.augmentation import (
    BackTranslationAugmentation,
    MultilingualBackTranslation,
    RoundTripTranslation,
    BackTranslationWithNoise,
    SynonymReplacement,
    EasyDataAugmentation,
    ContextualSynonymReplacement,
    RandomInsertion,
    RandomDeletion,
    RandomSwap,
    TextAugmenter,
    CharacterLevelAugmentation,
    BackRandomEdits,
    ContextualAugmentation,
    ConditionalContextualAugmentation,
    BERTContextualAugmentation,
    FillMaskAugmentation,
)

from fishstick.nlp_extensions.similarity import (
    cosine_similarity,
    cosine_distance,
    batch_cosine_similarity,
    CosineSimilarityScorer,
    SemanticSimilarity,
    levenshtein_distance,
    normalized_levenshtein,
    levenshtein_ratio,
    partial_ratio,
    token_sort_ratio,
    token_set_ratio,
    LevenshteinScorer,
    FuzzyMatcher,
    bleu_score,
    sentence_bleu,
    corpus_bleu,
    BLEUScorer,
    compute_bleu_details,
    rouge_1_score,
    rouge_2_score,
    rouge_l_score,
    rouge_lsum_score,
    rouge_score,
    ROUGEScorer,
    rouge_n_score,
    compute_rouge_details,
    BERTScorer,
    bertscore,
    bertscore_corpus,
)

__all__ = [
    # Tokenizers
    "BPETokenizer",
    "AdaptiveBPETokenizer",
    "ByteLevelBPETokenizer",
    "WordPieceTokenizer",
    "FastWordPieceTokenizer",
    "BertWordPieceTokenizer",
    "SentencePieceTokenizer",
    "UnigramSentencePiece",
    "BPESentencePiece",
    # Position Encoding
    "RotaryPositionalEmbedding",
    "RotaryEmbedding",
    "LinearRoPE",
    "YaRNScalingRotaryEmbedding",
    "apply_rotary_pos_emb",
    "MultiHeadRotaryAttention",
    "ALiBiAttention",
    "ALiBiPositionalEmbedding",
    "ALiBiMultiHeadAttention",
    "AliBiFlashAttention",
    "build_alibi_bias",
    "RelativePositionBias",
    "SinusoidalRelativePositionBias",
    "RelativePositionMultiHeadAttention",
    "T5RelativePositionBias",
    "ShawRelativePosition",
    "RelativePositionKeyValue",
    "relative_position_bucket",
    # Efficiency
    "GradientCheckpointing",
    "CheckpointWrapper",
    "ModularGradientCheckpointing",
    "checkpoint_wrapper",
    "create_gradient_checkpointing_function",
    "MixedPrecisionCheckpointing",
    "SelectiveCheckpointing",
    "RecomputationScheduler",
    "SparseAttention",
    "SlidingWindowAttention",
    "BlockSparseAttention",
    "DilatedAttention",
    "GlobalLocalAttention",
    "RandomAttention",
    "SparseMultiHeadAttention",
    "BigBirdAttention",
    "FlashAttention",
    "FlashAttentionV2",
    "MemoryEfficientAttention",
    "FlashMultiHeadAttention",
    "FlashAttentionWithPdrop",
    "is_flash_attn_available",
    "create_flash_attention",
    # Augmentation
    "BackTranslationAugmentation",
    "MultilingualBackTranslation",
    "RoundTripTranslation",
    "BackTranslationWithNoise",
    "SynonymReplacement",
    "EasyDataAugmentation",
    "ContextualSynonymReplacement",
    "RandomInsertion",
    "RandomDeletion",
    "RandomSwap",
    "TextAugmenter",
    "CharacterLevelAugmentation",
    "BackRandomEdits",
    "ContextualAugmentation",
    "ConditionalContextualAugmentation",
    "BERTContextualAugmentation",
    "FillMaskAugmentation",
    # Similarity
    "cosine_similarity",
    "cosine_distance",
    "batch_cosine_similarity",
    "CosineSimilarityScorer",
    "SemanticSimilarity",
    "levenshtein_distance",
    "normalized_levenshtein",
    "levenshtein_ratio",
    "partial_ratio",
    "token_sort_ratio",
    "token_set_ratio",
    "LevenshteinScorer",
    "FuzzyMatcher",
    "bleu_score",
    "sentence_bleu",
    "corpus_bleu",
    "BLEUScorer",
    "compute_bleu_details",
    "rouge_1_score",
    "rouge_2_score",
    "rouge_l_score",
    "rouge_lsum_score",
    "rouge_score",
    "ROUGEScorer",
    "rouge_n_score",
    "compute_rouge_details",
    "BERTScorer",
    "bertscore",
    "bertscore_corpus",
]
