"""
fishstick.distributions
======================

Comprehensive probability distributions and statistics module.

Provides:
- Core distribution classes and transformations
- Parameterized probability distributions
- Distribution transformations and flows
- Statistical testing utilities
- Distribution fitting algorithms
- Bayesian statistics primitives
- Monte Carlo sampling utilities
"""

from .core import (
    BaseDistribution,
    DistributionParams,
    NormalParams,
    TransformedDistribution,
    MixtureDistribution,
    CompositeDistribution,
    safe_scale,
    safe_prob,
    standardize,
    destandardize,
)

from .parameterized import (
    NormalDistribution,
    ExponentialDistribution,
    GammaDistribution,
    BetaDistribution,
    LaplaceDistribution,
    LogNormalDistribution,
    CategoricalDistribution,
    MultivariateNormalDistribution,
    DirichletDistribution,
    WishartDistribution,
    VonMisesFisherDistribution,
)

from .transforms import (
    AffineTransform,
    ExpTransform,
    LogTransform,
    SigmoidTransform,
    SoftplusTransform,
    MonotonicRationalQuadraticSpline,
    NeuralSplineTransform,
    CouplingTransform,
    ActNorm,
    PlanarFlow,
    RadialFlow,
    IAF,
    MADE,
)

from .statistics import (
    TestResult,
    ConfidenceInterval,
    t_test_1sample,
    t_test_2sample,
    paired_t_test,
    chi2_test,
    ks_test,
    shapiro_wilk_test,
    levene_test,
    mann_whitney_test,
    wilcoxon_test,
    kruskal_wallis_test,
    friedman_test,
    confidence_interval_mean,
    confidence_interval_proportion,
    bootstrap_ci,
    anova_oneway,
    effect_size_cohens_d,
    effect_size_eta_squared,
    multiple_testing_correction,
    permutation_test,
    bayes_factor,
)

from .fitting import (
    FitResult,
    DistributionFitter,
    NormalFitter,
    ExponentialFitter,
    GammaFitter,
    BetaFitter,
    PoissonFitter,
    WeibullFitter,
    LogNormalFitter,
    MultivariateNormalFitter,
    GaussianMixtureFitter,
    KernelDensityEstimator,
    fit_distribution,
    compare_distributions,
    select_best_distribution,
)

from .bayesian import (
    Prior,
    Posterior,
    NormalNormalConjugate,
    BetaBernoulliConjugate,
    GammaPoissonConjugate,
    MetropolisHastings,
    HamiltonianMonteCarlo,
    VariationalInference,
    BayesianModelAverage,
    EmpiricalBayes,
    BayesianLinearRegression,
    compute_log_marginal_likelihood,
    bayesian_information_criterion,
    akaike_information_criterion,
    ConjugateGradientDescent,
)

from .sampling import (
    SampleResult,
    ImportanceSampling,
    RejectionSampling,
    MetropolisHastingsSampler,
    GibbsSampling,
    HamiltonianSampler,
    ParticleFilter,
    AnnealedImportanceSampling,
    SliceSampling,
    RaoBlackwellization,
    AntitheticVariates,
    ControlVariates,
    effective_sample_size,
    stratified_sampling,
    latin_hypercube_sampling,
    sobol_sampling,
    bootstrap_sampling,
    jackknife_sampling,
)

__all__ = [
    # Core
    "BaseDistribution",
    "DistributionParams",
    "NormalParams",
    "TransformedDistribution",
    "MixtureDistribution",
    "CompositeDistribution",
    "safe_scale",
    "safe_prob",
    "standardize",
    "destandardize",
    # Parameterized distributions
    "NormalDistribution",
    "ExponentialDistribution",
    "GammaDistribution",
    "BetaDistribution",
    "LaplaceDistribution",
    "LogNormalDistribution",
    "CategoricalDistribution",
    "MultivariateNormalDistribution",
    "DirichletDistribution",
    "WishartDistribution",
    "VonMisesFisherDistribution",
    # Transforms
    "AffineTransform",
    "ExpTransform",
    "LogTransform",
    "SigmoidTransform",
    "SoftplusTransform",
    "MonotonicRationalQuadraticSpline",
    "NeuralSplineTransform",
    "CouplingTransform",
    "ActNorm",
    "PlanarFlow",
    "RadialFlow",
    "IAF",
    "MADE",
    # Statistics
    "TestResult",
    "ConfidenceInterval",
    "t_test_1sample",
    "t_test_2sample",
    "paired_t_test",
    "chi2_test",
    "ks_test",
    "shapiro_wilk_test",
    "levene_test",
    "mann_whitney_test",
    "wilcoxon_test",
    "kruskal_wallis_test",
    "friedman_test",
    "confidence_interval_mean",
    "confidence_interval_proportion",
    "bootstrap_ci",
    "anova_oneway",
    "effect_size_cohens_d",
    "effect_size_eta_squared",
    "multiple_testing_correction",
    "permutation_test",
    "bayes_factor",
    # Fitting
    "FitResult",
    "DistributionFitter",
    "NormalFitter",
    "ExponentialFitter",
    "GammaFitter",
    "BetaFitter",
    "PoissonFitter",
    "WeibullFitter",
    "LogNormalFitter",
    "MultivariateNormalFitter",
    "GaussianMixtureFitter",
    "KernelDensityEstimator",
    "fit_distribution",
    "compare_distributions",
    "select_best_distribution",
    # Bayesian
    "Prior",
    "Posterior",
    "NormalNormalConjugate",
    "BetaBernoulliConjugate",
    "GammaPoissonConjugate",
    "MetropolisHastings",
    "HamiltonianMonteCarlo",
    "VariationalInference",
    "BayesianModelAverage",
    "EmpiricalBayes",
    "BayesianLinearRegression",
    "compute_log_marginal_likelihood",
    "bayesian_information_criterion",
    "akaike_information_criterion",
    "ConjugateGradientDescent",
    # Sampling
    "SampleResult",
    "ImportanceSampling",
    "RejectionSampling",
    "MetropolisHastingsSampler",
    "GibbsSampling",
    "HamiltonianSampler",
    "ParticleFilter",
    "AnnealedImportanceSampling",
    "SliceSampling",
    "RaoBlackwellization",
    "AntitheticVariates",
    "ControlVariates",
    "effective_sample_size",
    "stratified_sampling",
    "latin_hypercube_sampling",
    "sobol_sampling",
    "bootstrap_sampling",
    "jackknife_sampling",
]
